version: '3.9'

services:

  main-service:
    container_name: "main-service"
    build:
      context: ./main_service
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./main_service:/app

  catalog-service:
    container_name: "catalogue-service"
    build:
      context: ./catalogue_service
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8791:8000'
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@catalog-db:5432/catalogue_db
    volumes:
      - ./catalogue_service:/app

  catalog-db:
    container_name: "catalogue-db"
    image: postgres
    restart: always
    ports:
      - '5438:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalogue_db
    volumes:
      - ./catalogue_db:/var/lib/postgresql/data
