version: '3.9'

services:

  fastapi:
    container_name: "fastapi"
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/pizza
    depends_on:
      - db

  db:
    container_name: "database"
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pizza
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5438:5432'

volumes:
  pgdata:
