"""new columns in order

Revision ID: ef1854fc26c6
Revises: 817b4372157f
Create Date: 2024-11-06 22:24:59.567551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1854fc26c6'
down_revision: Union[str, None] = '817b4372157f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('address', sa.String(), nullable=False))
    op.add_column('order', sa.Column('phone', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('order', 'phone')
    op.drop_column('order', 'address')
    # ### end Alembic commands ###
